AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-example

  Sample SAM Template for lambda-example

Globals:
  Function:
    Timeout: 3

Resources:
  SayHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: say_hello/
      Handler: app.lambda_handler
      Runtime: python3.7
